import { Logo } from "@briom/components/logo";
import { Container } from "@briom/components/ui/container";
import Link from "next/link";

export const metadata = {
	title: "Terms of Service — Briom",
	description: "The terms governing your use of Briom.",
};

function Section({
	title,
	children,
}: {
	title: string;
	children: React.ReactNode;
}) {
	return (
		<div className="mb-10">
			<h2 className="font-serif text-xl mb-3 text-foreground">{title}</h2>
			<div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
				{children}
			</div>
		</div>
	);
}

export default function TermsPage() {
	return (
		<main className="min-h-svh bg-background">
			{/* minimal nav */}
			<nav className="sticky top-0 z-10 border-b border-border/50 bg-background/80 backdrop-blur-sm">
				<Container>
					<div className="flex items-center min-h-16">
						<Link href="/">
							<Logo
								className="translate-y-1 text-muted-foreground/60"
								tagline
								tinted
							/>
						</Link>
					</div>
				</Container>
			</nav>

			<Container className="py-20 max-w-2xl">
				{/* header */}
				<div className="mb-14">
					<p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground mb-4">
						Legal
					</p>
					<h1 className="font-serif text-4xl sm:text-5xl leading-tight mb-4">
						Terms of Service
					</h1>
					<p className="text-sm text-muted-foreground font-mono">
						Last updated: June 2025
					</p>
				</div>

				<div>
					<Section title="1. Acceptance">
						<p>
							These Terms of Service ("Terms") govern your use of Briom
							("Service"), operated by Briom ("we", "us", "our"). By accessing
							or using Briom, you agree to be bound by these Terms. If you do
							not agree, do not use the Service.
						</p>
					</Section>

					<Section title="2. Description of Service">
						<p>
							Briom is a collaborative AI deliberation workspace. It allows you
							to create discussion rooms, invite AI model participants, and
							guide multi-perspective conversations on topics of your choice.
						</p>
						<p>
							Briom routes AI requests to third-party model providers via
							OpenRouter. The quality, accuracy, and content of AI-generated
							responses are subject to the capabilities and limitations of those
							underlying models.
						</p>
					</Section>

					<Section title="3. Eligibility">
						<p>
							You must be at least 13 years old to use Briom. By using the
							Service, you represent that you meet this requirement and that the
							information you provide during registration is accurate.
						</p>
					</Section>

					<Section title="4. Your Account">
						<p>
							You are responsible for maintaining the confidentiality of your
							account credentials and for all activity that occurs under your
							account. Notify us immediately if you suspect unauthorised access.
						</p>
						<p>
							We reserve the right to suspend or terminate accounts that violate
							these Terms or that we reasonably believe pose a risk to other
							users or to the integrity of the Service.
						</p>
					</Section>

					<Section title="5. Acceptable Use">
						<p>You agree not to use Briom to:</p>
						<ul className="list-disc pl-5 space-y-1">
							<li>
								Generate, distribute, or promote illegal content, including
								content that is defamatory, harassing, or violates any
								applicable law.
							</li>
							<li>
								Attempt to circumvent safety measures of any AI model provider.
							</li>
							<li>
								Interfere with or disrupt the Service or its underlying
								infrastructure.
							</li>
							<li>
								Collect or harvest personal data about other users without
								consent.
							</li>
							<li>
								Use the Service for purposes that violate the terms of any
								underlying AI model provider (including OpenAI, Anthropic, or
								Google).
							</li>
						</ul>
					</Section>

					<Section title="6. Your Content">
						<p>
							You retain ownership of the content you create and introduce into
							Briom rooms. By using the Service, you grant us a limited licence
							to store and process your content solely to provide the Service to
							you.
						</p>
						<p>
							You are solely responsible for the content you introduce into
							deliberations. We do not review deliberation content in real time
							and are not liable for content generated by AI participants.
						</p>
					</Section>

					<Section title="7. AI-Generated Content">
						<p>
							Responses generated by AI participants within Briom are produced
							by third-party AI models and do not represent the views or
							recommendations of Briom. AI-generated content may be inaccurate,
							incomplete, or inappropriate for your particular purpose.
						</p>
						<p>
							You should not rely on AI-generated content for legal, medical,
							financial, or other professional advice without independent
							verification.
						</p>
					</Section>

					<Section title="8. Intellectual Property">
						<p>
							The Briom name, logo, product design, and all associated
							intellectual property are owned by Briom. Nothing in these Terms
							grants you a right to use our trademarks or branding without prior
							written permission.
						</p>
					</Section>

					<Section title="9. Disclaimers">
						<p>
							Briom is provided "as is" and "as available" without warranties of
							any kind, express or implied. We do not warrant that the Service
							will be uninterrupted, error-free, or free of harmful components.
						</p>
					</Section>

					<Section title="10. Limitation of Liability">
						<p>
							To the fullest extent permitted by law, Briom shall not be liable
							for any indirect, incidental, consequential, or punitive damages
							arising from your use of or inability to use the Service, even if
							we have been advised of the possibility of such damages.
						</p>
						<p>
							Our total liability for any claim arising under these Terms shall
							not exceed the amount you paid us, if any, in the twelve months
							prior to the claim.
						</p>
					</Section>

					<Section title="11. Changes to the Service and Terms">
						<p>
							We may modify or discontinue the Service, or update these Terms,
							at any time. When we update the Terms, we will revise the "Last
							updated" date above. Continued use of Briom after changes
							constitutes your acceptance of the revised Terms.
						</p>
					</Section>

					<Section title="12. Governing Law">
						<p>
							These Terms are governed by applicable law. Any disputes arising
							from or relating to these Terms or the Service shall be subject to
							the exclusive jurisdiction of the competent courts in the
							applicable jurisdiction.
						</p>
					</Section>

					<Section title="13. Contact">
						<p>
							Questions about these Terms can be directed to{" "}
							<a
								className="text-primary underline underline-offset-3 hover:text-primary/80 transition-colors"
								href="mailto:hello@briom.app"
							>
								hello@briom.app
							</a>
							.
						</p>
					</Section>
				</div>

				{/* back link */}
				<div className="mt-16 pt-8 border-t border-border/50 flex items-center gap-4">
					<Link
						className="text-xs font-mono text-muted-foreground/60 hover:text-foreground transition-colors"
						href="/"
					>
						← Back to Briom
					</Link>
					<Link
						className="text-xs font-mono text-muted-foreground/60 hover:text-foreground transition-colors"
						href="/privacy"
					>
						Privacy Policy →
					</Link>
				</div>
			</Container>
		</main>
	);
}
