import {
	type DomainError,
	ValueObject,
	validator as v,
} from "@briom/libs/drimion";

import { InvalidUsageError } from "./errors";

interface CreditUsageProps {
	/**
	 * @description
	 * Tokens generated by the model for this turn.
	 */
	completionTokens: number;

	/**
	 * @description
	 * Raw cost in USD as reported by Provider.
	 * BCr deduction is calculated from this in the application layer —
	 * domain does not know about FX rates or markup.
	 */
	costUsd: number;

	/**
	 * @description
	 * Tokens consumed by the full conversation history sent to the model.
	 */
	promptTokens: number;
}

/**
 * @description
 * Token consumption and cost metadata for a settled participant turn.
 *
 * Populated once per turn from OpenRouter's usage payload.
 * Always null for moderator turns — they make no LLM calls.
 * Foundation for BCr deduction and analytics.
 */
export class CreditUsage extends ValueObject<CreditUsageProps> {
	private constructor(props: CreditUsageProps) {
		super(props);
	}

	public static override isValidProps(
		props: CreditUsageProps,
	): DomainError | undefined {
		if (v.number(props.promptTokens).isNegative()) {
			return new InvalidUsageError("promptTokens cannot be negative");
		}

		if (v.number(props.completionTokens).isNegative()) {
			return new InvalidUsageError("completionTokens cannot be negative");
		}

		if (v.number(props.costUsd).isNegative()) {
			return new InvalidUsageError("costUsd cannot be negative");
		}
	}

	/**
	 * @description
	 * Tokens generated by the model for this turn.
	 */
	public get completionTokens(): number {
		return this.get("completionTokens");
	}

	/**
	 * @description
	 * Raw cost in USD as reported by OpenRouter.
	 * BCr deduction is calculated from this in the application layer —
	 * domain does not know about FX rates or markup.
	 */
	public get costUsd(): number {
		return this.get("costUsd");
	}

	/**
	 * @description
	 * Tokens consumed by the full conversation history sent to the model.
	 */
	public get promptTokens(): number {
		return this.get("promptTokens");
	}

	/**
	 * @description
	 * Total tokens for this turn (prompt + completion).
	 */
	public get totalTokens(): number {
		return this.get("promptTokens") + this.get("completionTokens");
	}
}
