import type { IntentOption } from "@briom/core/domain";

/**
 * @description
 * Data transfer object for a single turn proposal.
 *
 * Represents a suggested next participant and intent within a deliberation,
 * generated by the `RoomDeliberation` domain service based on current
 * discussion context, history, and missing perspectives.
 */
export interface TurnProposalDTO {
	/**
	 * @description
	 * Confidence score (0.0–1.0) indicating how strongly this proposal
	 * fits the current deliberation context. Higher values indicate
	 * more natural, contextually appropriate suggestions.
	 */
	confidence: number;

	/**
	 * @description
	 * The suggested intent for this participant's next turn.
	 * Governs how the system prompt is constructed for the LLM call.
	 */
	intent: IntentOption;

	/**
	 * @description
	 * Rich, dynamic label for the proposal bubble in the UI.
	 * Generated from the `ProposalDictionary` — never static or robotic.
	 * Examples: "Claude wants to challenge this", "GPT sees a gap here",
	 * "Something bugs Gemini about this reasoning".
	 */
	label: string;

	/**
	 * @description
	 * Name of the participant to give perspective.
	 */
	name: string;

	/**
	 * @description
	 * Identifier of the proposed participant (AI model) to take the next turn.
	 */
	participantId: string;
}

/**
 * @description
 * Input for `GetTurnProposalsQuery`.
 *
 * MVP: only requires room ID. The domain service derives all context
 * (turn history, participant roster, current state) from the room.
 */
export interface GetTurnProposalsInput {
	/**
	 * @description
	 * Room to generate proposals for.
	 */
	roomId: string;
}

/**
 * @description
 * Output from `GetTurnProposalsQuery`.
 *
 * Returns zero or more proposals, sorted by confidence descending.
 * Empty array indicates no valid proposals (e.g., room not deliberating,
 * no participants, or deliberation concluded).
 */
export interface GetTurnProposalsOutput {
	/**
	 * @description
	 * Suggested next turns, ranked by confidence.
	 * FE renders as contextual suggestion bubbles below settled turns.
	 */
	proposals: TurnProposalDTO[];
}

/**
 * @description
 * `GetTurnProposalsQuery` — Application Query Port
 *
 * Contract for retrieving AI-generated turn proposals within a deliberation.
 * Delegates to `RoomDeliberation.proposeNextTurns()` for context-aware
 * suggestion generation.
 *
 * **Why a Port?**
 * Proposal generation is a domain concern (requires turn history, participant
 * analysis, intent validation). The application layer defines the contract;
 * the domain service implements the logic.
 *
 * **Usage**
 * Called by the FE after each turn settles to populate suggestion bubbles.
 * Proposals are ephemeral — not persisted, regenerated on each query.
 *
 * @see RoomDeliberation.proposeNextTurns — domain logic
 * @see DrizzleGetTurnProposalsQuery — infrastructure implementation
 */
export interface GetTurnProposalsQuery {
	/**
	 * @description
	 * Generates contextual turn proposals for the given room.
	 *
	 * @param input - Room ID to analyze
	 * @returns Ranked proposals, or empty if no valid suggestions
	 */
	execute(input: GetTurnProposalsInput): Promise<GetTurnProposalsOutput>;
}
