import type { TurnIntent } from "@briom/domain";

/**
 * @description
 * Data transfer object for a single turn proposal.
 *
 * Represents a suggested next participant and intent within a deliberation,
 * generated by the `RoomDeliberation` domain service based on current
 * discussion context, history, and missing perspectives.
 */
export interface TurnProposalDTO {
	/**
	 * @description
	 * Confidence score (0.0–1.0) indicating how strongly this proposal
	 * fits the current deliberation context. Higher values indicate
	 * more natural, contextually appropriate suggestions.
	 */
	confidence: number;

	/**
	 * @description
	 * The suggested intent for this participant's next turn.
	 * Governs how the system prompt is constructed for the LLM call.
	 */
	intent: TurnIntent;

	/**
	 * @description
	 * Rich, dynamic label for the proposal bubble in the UI.
	 * Generated from the `ProposalDictionary` — never static or robotic.
	 * Examples: "Claude wants to challenge this", "GPT sees a gap here",
	 * "Something bugs Gemini about this reasoning".
	 */
	label: string;

	/**
	 * @description
	 * Name of the participant to give perspective.
	 */
	name: string;

	/**
	 * @description
	 * Identifier of the proposed participant (AI model) to take the next turn.
	 */
	participantId: string;
}
