import * as pg from "drizzle-orm/pg-core";

import { roomsTable } from "./rooms.schema";
import { roomSchema } from "./schema";

/**
 * @description
 * Database schema for `Checkpoint` entity persistence.
 */
export const checkpointsTable = roomSchema.table(
	"checkpoints",
	{
		/**
		 * @description
		 * Unique checkpoint identifier (UUID).
		 */
		id: pg.uuid().primaryKey(),

		/**
		 * @description
		 * The Room this checkpoint summarizes.
		 */
		roomId: pg
			.uuid()
			.notNull()
			.references(() => roomsTable.id, { onDelete: "cascade" }),

		/**
		 * @description
		 * Cumulative summary of the deliberation up to `coverSequences`.
		 */
		content: pg.text().notNull(),

		/**
		 * @description
		 * The highest turn sequence this checkpoint accounts for.
		 */
		coverSequences: pg.integer().notNull(),

		/**
		 * @description
		 * Which generation this is within the room — 1st, 2nd checkpoint, etc.
		 */
		iteration: pg.integer().notNull(),

		/**
		 * @description
		 * Qualified model that successfully produced this checkpoint.
		 */
		generatedBy: pg.text().notNull(),

		/**
		 * @description
		 * The checkpoint this one was built from, or null if this is the first.
		 */
		previousCheckpointId: pg.uuid(),

		/**
		 * @description
		 * Tokens consumed by the full conversation history.
		 */
		usagePromptTokens: pg.integer(),

		/**
		 * @description
		 * Tokens generated by the model for this checkpoint.
		 */
		usageCompletionTokens: pg.integer(),

		/**
		 * @description
		 * Raw cost in USD as reported by the provider.
		 */
		usageCostUsd: pg.real(),

		/**
		 * @description
		 * When this checkpoint was generated.
		 */
		createdAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [
		pg
			.index("checkpoint_room_latest_idx")
			.on(table.roomId, table.createdAt.desc()),
	],
);
