import * as pg from "drizzle-orm/pg-core";

import { moderatorsTable } from "./moderators.schema";

/**
 * @description
 * Database schema for `CreditMovement` entity persistence.
 */
export const creditMovementsTable = pg.snakeCase.table(
	"credit_movements",
	{
		/**
		 * @description
		 * Unique movement identifier (UUID), generated by the domain layer.
		 */
		id: pg.uuid().primaryKey(),

		/**
		 * @description
		 * The Moderator whose balance moved.
		 */
		moderatorId: pg
			.uuid()
			.notNull()
			.references(() => moderatorsTable.id, { onDelete: "cascade" }),

		/**
		 * @description
		 * BCr involved. Positive = added, negative = spent.
		 */
		amount: pg.real().notNull(),

		/**
		 * @description
		 * What triggered the movement — `credit_deducted` | `credit_topped_up` | `credit_granted`.
		 */
		type: pg
			.text({ enum: ["credit_deducted", "credit_topped_up", "credit_granted"] })
			.notNull(),

		/**
		 * @description
		 * Human-readable context.
		 */
		reason: pg.text().notNull(),

		/**
		 * @description
		 * When this movement was recorded.
		 */
		createdAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [
		pg
			.index("credit_movement_moderator_audit_idx")
			.on(table.moderatorId, table.createdAt.asc()),
	],
);
