import * as pg from "drizzle-orm/pg-core";

import { roomsTable } from "./rooms.schema";

/**
 * @description
 * Database schema for `Participant` entity persistence.
 */
export const participantsTable = pg.snakeCase.table(
	"participants",
	{
		/**
		 * @description
		 * Unique participant identifier (UUID), generated by the domain layer.
		 */
		id: pg.uuid().primaryKey(),

		/**
		 * @description
		 * The Room this Participant belongs to.
		 */
		roomId: pg
			.uuid()
			.notNull()
			.references(() => roomsTable.id, { onDelete: "cascade" }),

		/**
		 * @description
		 * Human-readable name shown in the room UI.
		 */
		displayName: pg.text().notNull(),

		/**
		 * @description
		 * The AI model identifier powering this participant.
		 */
		model: pg.text().notNull(),

		/**
		 * @description
		 * The model provider identifier.
		 */
		provider: pg.text().notNull(),

		/**
		 * @description
		 * When this Participant was invited into the Room.
		 */
		createdAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),

		/**
		 * @description
		 * When this Participant was last mutated (e.g. renamed).
		 */
		updatedAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [pg.index("room_id_idx").on(table.roomId)],
);
