import * as pg from "drizzle-orm/pg-core";

import { moderatorsTable } from "./moderators.schema";

/**
 * @description
 * Database schema for `Room` aggregate persistence.
 */
export const roomsTable = pg.snakeCase.table(
	"rooms",
	{
		/**
		 * @description
		 * Unique room identifier (UUID), generated by the domain layer.
		 */
		id: pg.uuid().primaryKey(),

		/**
		 * @description
		 * The Moderator who opened this Room.
		 */
		moderatorId: pg
			.uuid()
			.notNull()
			.references(() => moderatorsTable.id, { onDelete: "cascade" }),

		/**
		 * @description
		 * Human-readable name for the Room.
		 */
		title: pg.text().notNull(),

		/**
		 * @description
		 * Room status lifecycle: `forming` | `deliberating` | `concluded`.
		 */
		status: pg
			.text({ enum: ["forming", "deliberating", "concluded"] })
			.notNull()
			.default("forming"),

		/**
		 * @description
		 * The central question driving deliberation.
		 */
		topic: pg.text(),

		/**
		 * @description
		 * Why this Room currently rejects new turns, or null if it doesn't.
		 */
		stateKind: pg.text({ enum: ["frozen", "locked"] }),

		/**
		 * @description
		 * Human-readable explanation for the current `stateKind`.
		 */
		stateReason: pg.text(),

		/**
		 * @description
		 * When the current `stateKind` was applied.
		 */
		stateOccurredAt: pg.timestamp({ withTimezone: true }),

		/**
		 * @description
		 * The Turn currently claimed for in-flight contribution.
		 */
		activeTurnId: pg.uuid(),

		/**
		 * @description
		 * Cumulative number of files attached across all moderator turns.
		 */
		attachmentCount: pg.integer().notNull().default(0),

		/**
		 * @description
		 * Ordered list of Turn IDs registered in this Room, oldest first.
		 */
		turnIds: pg.jsonb().notNull().default([]).$type<string[]>(),

		/**
		 * @description
		 * Ordered list of Checkpoint IDs attached to this Room, oldest first.
		 */
		checkpointIds: pg.jsonb().notNull().default([]).$type<string[]>(),

		/**
		 * @description
		 * When this Room was formed.
		 */
		createdAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),

		/**
		 * @description
		 * When this Room's state was last mutated.
		 */
		updatedAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [
		pg
			.index("rooms_moderator_updated_idx")
			.on(table.moderatorId, table.updatedAt.desc()),
	],
);
