import * as pg from "drizzle-orm/pg-core";

import { roomsTable } from "./rooms.schema";

/**
 * @description
 * Database schema for `Turn` aggregate persistence.
 */
export const turnsTable = pg.snakeCase.table(
	"turns",
	{
		/**
		 * @description
		 * Unique turn identifier (UUID), generated by the domain layer.
		 */
		id: pg.uuid().primaryKey(),

		/**
		 * @description
		 * The Room this Turn belongs to.
		 */
		roomId: pg
			.uuid()
			.notNull()
			.references(() => roomsTable.id, { onDelete: "cascade" }),

		/**
		 * @description
		 * Ordinal position of this turn within the room's deliberation.
		 */
		sequence: pg.integer().notNull(),

		/**
		 * @description
		 * Who authored this turn — `moderator` or `participant`.
		 */
		authorType: pg.text({ enum: ["moderator", "participant"] }).notNull(),

		/**
		 * @description
		 * The ModeratorId or ParticipantId of whoever authored this turn.
		 */
		authorId: pg.uuid().notNull(),

		/**
		 * @description
		 * Why this participant is contributing now. Null for moderator turns.
		 */
		intent: pg.text({
			enum: [
				"challenge",
				"critique",
				"direct",
				"expand",
				"respond",
				"summarize",
			],
		}),

		/**
		 * @description
		 * The turn that immediately precedes this one in the deliberation chain.
		 */
		previousTurnId: pg.uuid(),

		/**
		 * @description
		 * Current lifecycle state: `pending` | `streaming` | `settled` | `failed` | `abandoned`.
		 */
		status: pg
			.text({
				enum: ["pending", "streaming", "settled", "failed", "abandoned"],
			})
			.notNull()
			.default("pending"),

		/**
		 * @description
		 * Readable content for this turn.
		 */
		content: pg.text(),

		/**
		 * @description
		 * When this turn settled.
		 */
		settledAt: pg.timestamp({ withTimezone: true }),

		/**
		 * @description
		 * Stream failure classification — `timeout` | `rate_limited` | ...
		 */
		errorKind: pg.text({
			enum: [
				"timeout",
				"rate_limited",
				"model_not_found",
				"stream_failure",
				"aborted",
				"empty_response",
			],
		}),

		/**
		 * @description
		 * Human-readable description of the stream failure.
		 */
		errorMessage: pg.text(),

		/**
		 * @description
		 * Seconds to wait before retrying, if the provider specified one.
		 */
		errorRetryAfter: pg.integer(),

		/**
		 * @description
		 * When this turn failed.
		 */
		failedAt: pg.timestamp({ withTimezone: true }),

		/**
		 * @description
		 * Files shared alongside a moderator turn, embedded as a JSON array.
		 */
		attachments: pg.jsonb().notNull().default([]).$type<
			Array<{
				mediaType: "text" | "image";
				mimeType: string;
				name: string;
				sizeBytes: number;
				url: string;
				content:
					| { mediaType: "text"; text: string }
					| { mediaType: "image"; base64: string };
			}>
		>(),

		/**
		 * @description
		 * Tokens consumed by the full conversation history sent to the model.
		 */
		usagePromptTokens: pg.integer(),

		/**
		 * @description
		 * Tokens generated by the model for this turn.
		 */
		usageCompletionTokens: pg.integer(),

		/**
		 * @description
		 * Raw cost in USD as reported by the provider.
		 */
		usageCostUsd: pg.real(),

		/**
		 * @description
		 * Flags the turn to be aborted on next tick.
		 */
		abortRequested: pg.boolean().default(false),

		/**
		 * @description
		 * When this turn was first initiated.
		 */
		createdAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),

		/**
		 * @description
		 * When this turn's state was last mutated.
		 */
		updatedAt: pg.timestamp({ withTimezone: true }).notNull().defaultNow(),
	},
	(table) => [
		pg.index("turn_room_sequence_idx").on(table.roomId, table.sequence.desc()),
	],
);
