import {
	BOLD_ITALIC_STAR,
	BOLD_ITALIC_UNDERSCORE,
	BOLD_STAR,
	BOLD_UNDERSCORE,
	INLINE_CODE,
	ITALIC_STAR,
	ITALIC_UNDERSCORE,
	ORDERED_LIST,
	STRIKETHROUGH,
	type Transformer,
	UNORDERED_LIST,
} from "@lexical/markdown";

export const CONVERSATION_INPUT_TRANSFORMERS: Transformer[] = [
	BOLD_ITALIC_STAR,
	BOLD_ITALIC_UNDERSCORE,
	BOLD_STAR,
	BOLD_UNDERSCORE,
	ITALIC_STAR,
	ITALIC_UNDERSCORE,
	STRIKETHROUGH,
	INLINE_CODE,
	UNORDERED_LIST,
	ORDERED_LIST,
];
