import type { EditorThemeClasses } from "lexical";

export const moderatorEditorTheme: EditorThemeClasses = {
	code: "rounded-lg bg-muted p-3 font-mono text-sm my-2 block",
	codeHighlight: {
		atrule: "text-sky-400",
		attr: "text-sky-400",
		"attr-name": "text-sky-400",
		"attr-value": "text-emerald-400",
		boolean: "text-amber-400",
		builtin: "text-sky-400",
		cdata: "text-muted-foreground",
		char: "text-emerald-400",
		class: "text-sky-400",
		"class-name": "text-sky-400",
		comment: "text-muted-foreground italic",
		constant: "text-amber-400",
		deleted: "text-rose-400",
		doctype: "text-muted-foreground",
		entity: "text-amber-400",
		function: "text-amber-400",
		important: "text-rose-400",
		inserted: "text-emerald-400",
		keyword: "text-sky-400",
		namespace: "text-sky-400",
		number: "text-amber-400",
		operator: "text-foreground/70",
		prolog: "text-muted-foreground",
		property: "text-sky-400",
		punctuation: "text-foreground/50",
		regex: "text-emerald-400",
		selector: "text-emerald-400",
		string: "text-emerald-400",
		symbol: "text-amber-400",
		tag: "text-rose-400",
		url: "text-emerald-400",
		variable: "text-amber-400",
	},
	link: "text-dusty-blue hover:text-dusty-blue/80 cursor-pointer",
	list: {
		listitem: "",
		ol: "list-decimal px-5 my-1! space-y-0.5 mx-2",
		ul: "list-disc px-5 my-1 space-y-0.5 mx-2",
	},
	paragraph: "my-2!",
	text: {
		code: "rounded bg-muted text-muted-foreground/75 px-1 py-0.5 font-mono text-sm",
	},
};
