import type { AttachmentContent, TurnIntent } from "@briom/core/domain";

/**
 * @description
 * Input data required to execute the `InitiateTurn` command.
 */
export interface InitiateTurnInput {
	/**
	 * @description
	 * List of attachments included in the moderator's turn.
	 * @default []
	 */
	attachments?: {
		/**
		 * @description
		 * Parsed content produced by the Front-End before uploading:
		 * - `TEXT`: Raw plain text string extracted from the file.
		 * - `IMAGE`: Base64-encoded Data URI to be forwarded directly to the LLM.
		 */
		content: AttachmentContent;

		/**
		 * @description
		 * Full MIME type string as reported by the browser.
		 * @example "image/jpeg", "text/plain"
		 */
		mimeType: string;

		/**
		 * @description
		 * Original filename of the uploaded file.
		 */
		name: string;

		/**
		 * @description
		 * Raw file size measured in bytes.
		 */
		sizeBytes: number;

		/**
		 * @description
		 * External storage URL (e.g., Supabase Storage) used for rendering the file component in the UI.
		 */
		url: string;
	}[];

	/**
	 * @description
	 * The core message content typed and sent by the moderator.
	 */
	content: string;

	/**
	 * @description
	 * List of participant IDs explicitly mentioned by the moderator in this turn.
	 * Each ID must follow the UUID v4 format.
	 * @default []
	 */
	mentionedParticipantIds: string[];

	/**
	 * @description
	 * The ID of the moderator performing this action. Used for authorization (Auth-Z) checks.
	 * Format: UUID v4.
	 */
	moderatorId: string;

	/**
	 * @description
	 * An optional, optimistic ID generated by the Front-End to enable optimistic rendering
	 * with a stable component key. If omitted, the Back-End will automatically generate
	 * a new ID and return it within the HTTP response.
	 * Format: UUID v4.
	 */
	moderatorTurnId?: string;

	/**
	 * @description
	 * The ID of the room where this turn is being processed and stored.
	 * Format: UUID v4.
	 */
	roomId: string;
}

/**
 * @description
 * Output data returned after the `InitiateTurn` command executes successfully.
 */
export interface InitiateTurnOutput {
	/**
	 * @description
	 * Attachments that failed domain validation (unsupported MIME, size
	 * limit exceeded, etc.) and were silently excluded from the moderator
	 * turn. Empty array when every attachment was accepted. FE should
	 * surface each entry as a toast/inline error — the turn itself still
	 * succeeds with whatever attachments passed validation.
	 * @default []
	 */
	failedAttachments: {
		/**
		 * @description
		 * Original filename of the attachment that failed validation.
		 */
		name: string;

		/**
		 * @description
		 * Human-readable reason the attachment was rejected.
		 */
		reason: string;
	}[];

	/**
	 * @description
	 * Information about the acting moderator and the newly created turn.
	 */
	moderator: {
		/**
		 * @description
		 * The unique identifier of the moderator who triggered the action.
		 */
		id: string;

		/**
		 * @description
		 * Summary of the settled turn entity belonging to the moderator.
		 */
		turn: {
			/**
			 * @description
			 * The unique identifier of the moderator's turn.
			 */
			id: string;
		};
	};

	/**
	 * @description
	 * Information regarding the next participant selected by the system to respond to this turn.
	 */
	nextResponder: {
		/**
		 * @description
		 * Profile details of the selected responder. This data is critical for the Front-End
		 * to immediately render a skeleton/thinking card component placeholder in the UI.
		 */
		participant: {
			/**
			 * @description
			 * The unique identifier of the participant (AI/LLM Participant).
			 * Used to identify the card placeholder.
			 */
			id: string;

			/**
			 * @description
			 * Display name of the participant to be rendered on the skeleton loader card.
			 */
			displayName: string;

			/**
			 * @description
			 * The qualified model name of the LLM (e.g., `gpt-4o`, `claude-3-5-sonnet`).
			 * Useful for displaying specific model badges on the loading skeleton.
			 */
			qualifiedModel: string;
		};

		/**
		 * @description
		 * Summary of the pending draft turn entity generated for the participant.
		 */
		turn: {
			/**
			 * @description
			 * The unique identifier of the participant's pending turn.
			 */
			id: string;

			/**
			 * @description
			 * The calculated purpose or conversational intent of the upcoming participant turn.
			 */
			intent: TurnIntent;
		};
	};
}

/**
 * @description
 * A command that orchestrates flow of turn sequencing following
 * Moderator presents Participant respond afterwards. Next respondent
 * can be controlled by mentioning them or the system will pick it automatically.
 */
export class InitiateTurnCommand {
	public constructor(public readonly input: InitiateTurnInput) {}
}
