"use client";

import type { RoomDTO } from "@briom/app";
import {
	AccordionContent,
	AccordionExpander,
	AccordionItem,
} from "@briom/components/ui/accordion";
import { Button } from "@briom/components/ui/button";
import { ExpandIcon } from "lucide-react";

interface RoomSynthesisProps {
	onOpenSheet?: () => void;
	synthesis: RoomDTO["synthesis"];
	synthesisCreatedAt: RoomDTO["synthesisCreatedAt"];
	synthesisCreatedBy: RoomDTO["synthesisCreatedBy"];
	synthesisStatus: RoomDTO["synthesisStatus"];
}

export function RoomSynthesis({
	synthesis,
	synthesisStatus,
	synthesisCreatedBy,
	synthesisCreatedAt,
	onOpenSheet,
}: RoomSynthesisProps) {
	if (!synthesis && synthesisStatus === "idle") return null;

	const isCompleted = synthesisStatus === "completed" && synthesis;
	const isPending = synthesisStatus === "pending";
	const isFailed = synthesisStatus === "failed";

	return (
		<AccordionItem value="synthesis">
			<AccordionExpander title="Synthesis">
				<Button
					className="text-muted-foreground/50 hover:text-muted-foreground"
					onClick={(e) => {
						e.stopPropagation();
						onOpenSheet?.();
					}}
					size="icon-xs"
					variant={"ghost"}
				>
					<ExpandIcon />
				</Button>
			</AccordionExpander>
			<AccordionContent className="border-t p-4">
				<div className="flex flex-col gap-3">
					{isCompleted && (
						<div className="flex flex-col gap-1 text-sm">
							{synthesisCreatedAt && (
								<p className="text-xs text-muted-foreground">
									Synthesis generated at{" "}
									<span className="font-medium text-foreground">
										{new Date(synthesisCreatedAt).toLocaleString()}
									</span>{" "}
									by{" "}
									<span className="font-medium text-foreground">
										{synthesisCreatedBy}
									</span>
								</p>
							)}
						</div>
					)}

					{isPending && (
						<p className="text-sm text-muted-foreground animate-pulse">
							Synthesis is being generated by the selected participant...
						</p>
					)}

					{isFailed && (
						<p className="text-sm text-muted-foreground">
							Synthesis generation failed. You can try again by clicking the
							Synthesize button in the toolbar.
						</p>
					)}
				</div>
			</AccordionContent>
		</AccordionItem>
	);
}
